title: Your Resume
resume:
  name: 你的名字
  jobtitle: 你的岗位
  avatar: "images/a.JPG"

  contact:
    - icon: fa-rss
      text: 个人主页
      link: https://baidu.com/
    - icon: fa-github
      text: Github
      link: https://github.com/
    - icon: fa-envelope
      text: 邮箱
      link: mailto:yourmail@gmail.com
    - icon: fa-phone-square
      text: 110
  profiles:
    

  overview: 关关雎鸠，在河之洲。窈窕淑女，君子好逑。参差荇菜，左右流之。窈窕淑女，寤寐求之。求之不得，寤寐思服。悠哉悠哉，辗转反侧。参差荇菜，左右采之。窈窕淑女，琴瑟友之。参差荇菜，左右芼之。窈窕淑女，钟鼓乐之。
  #   level: beginner, intermediate, advanced, master
  skills:
    - title: 主修课程
      level: master
      items: [计算机组成原理, 操作系统, 计算机网络, 数据结构与算法, 编译原理, ···]
    - title: 主要技能
      level: advanced
      items: [Java, Spring, Spring Cloud, Mybatis, Mysql, ···]
    - title: 其他
      level: intermediate
      items: [Linux, 深度学习, IOS开发, Android开发, 爬虫, ···]
      
  experience:
    - position: 软件工程师
      duration: 2022.07 - Now
      company: Your 1st, Inc.
      website: https://rioslab.org
      description: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
      hilights: [
        Optimized an algorithm that holds the current world record for Weisman Scores,
        Hilight 2,
        Hilight 3,
      ]

      # Education
  education:
    - institution: 家伦敦大学
      course: 软件工程 · 本科
      duration: 2018.09 - 2022.6
      location: xx省 xx市 xx区 xx路 xx号
      location_url: 'https://baidu.com/'
      major: Lorem ipsum dolor sit amet

# Showcase your work
  projects:

  - title: 你的项目
    description: 你的项目简介
    duration: 2020.08 - 2021.06
    contribution: Maintainer
    hilights: [
      负责整个项目的xxx；,
    ]

  rewards:
    scholarship:
      - title: 家里蹲大学 · 三好学生（ 2020 ）
        description: 家里蹲大学
        date: 2020 & 2021

    competition:
      - title: xxx大赛 · x奖 （ 2021.08 ）
        description: 
        date: 2021 年 08 月

# Langguages Known 
# proficiency: beginner, intermediate, advanced, master, fluent, native speaker
  languages:
  - name: 英语 CET - 4
    proficiency: master
  - name: 英语 CET - 6
    proficiency: fluent

  update: '2022/01/08'